### ISSUE TITLE
Close new tweet panel

### ISSUE THREAD

**Issue by babie** [r7kamura/tweetdeck-shortcut-plus#8]
I want a shortcut to close new tweet panel.

ja: 新規ツイートパネルをやっぱええわというときに閉じるショートカット(ESC?)が欲しい。

**Comment by r7kamura** [comment]
Pro tips: press the Escape key twice to close it.

実はESC二度押しで閉じられます。(これを一度にしたいという話だったらすみません)

**Comment by babie** [comment]
Oh, I didn't know it.
知りませんでした。（恥ずかしい）

**Comment by r7kamura** [comment]
ヘルプ等で全く説明されていないはずなので仕方がない。

ダイレクトメッセージは "D" キーで呼び出せると説明されている一方で実は "M" キーでも呼び出せる、など説明されていない公式ショートカットキーも幾つかあるらしいです。
